export const labels = {
  contentSkipLink: 'Ga naar de inhoud',
  mainNavigation: 'Hoofdnavigatie',
  cookieBannerClose: 'Sluiten',
  settingsOverlayTrigger: 'Voorkeuren',
  settingsOverlayTitle: 'Weergaveopties',
  setttingsOverlayClose: 'Verberg voorkeuren',
  settingNotStoredTitle: 'Voorkeuren worden niet bewaard',
  sliderNextSlideLabel: 'Volgende slide',
  sliderPreviousSlideLabel: 'Vorige slide',
  latestNews: 'Laatste nieuws',
  regionalNewsOnboardingTitle: 'Kies je omroep',
  regionalNewsFormTitle: 'Volg het nieuws uit jouw regio',
  regionalNewsFormClose: 'Sluiten',
  regionalNewsArticleIndicator: 'In samenwerking met',
  regionalNewsOverviewLabel: 'Regionaal nieuws',
  videoPlayButtonLabel: 'Play',
  videoPauseButtonLabel: 'Pause',
  videoReplayButtonLabel: 'Replay',
  videoMuteButtonLabel: 'Mute',
  videoFullScreenButtonLabel: 'Fullscreen',
  videoProgressBarLabel: 'Progress bar',
} as const;
